# Configuration Mémoire Gradle Daemon pour éviter OutOfMemoryError
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Optimisations Android et Kotlin
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
kotlin.incremental=true
ksp.incremental=true
